#!/usr/bin/env bash
# Sets up an nginx web server that states text when curl command enacted
sudo apt-get -y update
sudo apt-get install -y nginx
sudo bash -c 'echo "Holberton School" > /var/www/html/index.nginx-debian.html'
sudo service nginx start
