#!/usr/bin/env bash
# Sets up an nginx web server that states text when curl command enacted
apt-get -y update
apt-get install -y nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
service nginx start
