#!/usr/bin/env bash
# Sets up an nginx web server that states text when curl command enacted
sudo apt-get -y update
sudo apt-get install -y nginx
echo "Holberton School" > /var/www/html/index.html
sudo service reload nginx
