#!/usr/bin/env bash
# Creates a redirection
sudo apt-get -y update
sudo apt-get -y install nginx
sudo bash -c 'echo "Holberton School" > /var/www/html/index.nginx-debian.html'
sudo bash -c 'sed -i "/server_name _;/ a\\\trewrite ^/redirect_me https:\/\/www.youtube.com/watch?v=gtdnMWMWN3o permanent;" /etc/nginx/sites-available/default'
sudo service nginx start
