#!/usr/bin/env bash
# Adds 404 Error page
sudo apt-get -y update
sudo apt-get -y install nginx
new="104.196.155.186;\n\tlocation \/redirect_me{\n\t\treturn 301 http:\/\/www.google.com;}"
sudo sed -i "s/localhost;/$new/" /etc/nginx/sites-available/default
sudo sed -i "s/#error_page 404/error_page 404/" /etc/nginx/sites-available/default
sudo touch /usr/share/nginx/html/404.html
sudo bash -c 'echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html'
sudo service nginx restart
