#!/usr/bin/env bash
# Installation and configuration of HAproxy load balancer with two servers with round roundrobin
apt-get update
apt-get install software-properties-common -y
apt-add-repository ppa:vbernat/haproxy-2.0 -y
apt-get update
apt-get install haproxy -y
apt-get install policycoreutils -y
printf "\nfrontend http_front\n\tbind *:80\n\tmode http\n\tdefault_backend http_back\n\nbackend http_back\n\tbalance roundrobin\n\tserver 660-web-01 104.196.155.186 check\n\tserver 660-web-02 34.74.71.83 check\n" >> /etc/haproxy/haproxy.cfg
service haproxy restart
