#!/usr/bin/env bash
# Sites enabled and sites available folders are not the same (Debugging)
sed -i 's/listen 8080 default_server;/listen 80 default_server;/' /etc/nginx/sites-enabled/default
sed -i 's/listen \[::\]:8080 default_server ipv6only=on;/listen \[::\]:80 default_server ipv6only=on;/' /etc/nginx/sites-enabled/default
service nginx restart
