#!/usr/bin/env bash
# (shows all curr running proccesses) A : Select all processes, u : Select all processes on a terminal, including those of other users, x : Select processes without controlling ttys
ps -auxf
