#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times and 9th is "Hi" using while
i="0"
while [ $i -lt 10 ]; do
echo "Holberton School"
if [ $i -eq 8 ];
then
echo "Hi"
fi
((i++))
done
