#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times and additional statements on 4 & 8 using while
i="1"
while [ $i -lt 11 ]; do
if [ $i -eq 4 ];
then
echo "bad luck"
elif [ $i -eq 8 ];
then
echo "good luck"
else echo "Holberton School"
fi
((i++))
done
