#!/usr/bin/env bash
# This script is displaying numbers 1-20 and additional script on 4/9/17 using while
i="1"
while [ $i -lt 21 ]; do
echo "$i"
if [ $i -eq 4 ];
then
echo "bad luck from China"
elif [ $i -eq 9 ];
then
echo "bad luck from Japan"
elif [ $i -eq 17 ];
then
echo "bad luck from Italy"
fi
((i++))
done
