#!/usr/bin/env bash
# Prints clock 12 hours and 59 minutes using while
hour="0"
while [ $hour -lt 13 ]; do
    min="1"
    echo "Hour: $hour"
    while [ $min -lt 60 ]
    do
        echo "$min"
        ((min++))
    done
    ((hour++))
done
