#!/usr/bin/env bash
# localhost resolves to 127.0.0.2 and facebook.com resolves to 8.8.8.8
cp /etc/hosts hosts_new
sed -i s/^127.*/"127.0.0.2 localhost"/ hosts_new
echo "8.8.8.8 facebook.com" >> hosts_new
cp hosts_new /etc/hosts
